export const offerList = [
  {
    createdAt: "2025-03-10T11:25:38.264Z",
    id: "31",
    offerId: "131729710-online:en:GB:1364469",
    title: "Nike Shox TL Men's Shoes - Black",
    description:
      "The Nike Shox TL takes mechanical cushioning to the next level.A recrafted version of the 2003 icon, it features breathable mesh in the upper, with full-length Nike Shox technology for optimal impact absorption and a bold look on the streets. Benefits:Nike Shox technology combines resilient, flexible columns with moderator plates for outstanding cushioning that compresses and regains its shape.A combination upper with a full TPU cage is a near-exact replica of the 2003 Nike Shox TL.Moulded overlays throughout the midfoot provide support and a snug fit.A TPU plate in the heel between the midsol",
    url: "https://www.nike.com/gb/t/shox-tl-shoes-TrpTJY3H/AV3595-004?CP=EUNS_AFF_AWIN_UK_376257_httpwwwprijswatchernl_169843&utm_source=httpwwwprijswatchernl&utm_medium=affiliate&utm_campaign=376257&utm_content=169843&sv1=affiliate&sv_campaign_id=376257&awc=16327_1744983458_adbe768ab6092662fc103fe25d163bdd",
    image: "https://img.shoparize.com/products/9YadFTXFYHj.jpg",
    contentLanguage: "en",
    targetCountry: "GB",
    availability: "in stock",
    brand: "Nike",
    condition: "new",
    price: {
      value: "154.99",
      currency: "GBP",
    },
    isSale: true,
    freeShipping: true,
    category: "sportswear",
    shop: "nike.com",
    shopImage:
      "https://www.pixartprinting.it/blog/wp-content/uploads/2023/12/1995-1024x561.jpg",
    rating: "4.9",
    payments: [
      "https://www.mastercard.com/content/dam/public/mastercardcom/vn/vi/logos/mastercard-og-image.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Visa_Inc._logo.svg/1024px-Visa_Inc._logo.svg.png",
      "https://rgb.vn/wp-content/uploads/2014/05/rgb_vn_new_branding_paypal_2014_logo_detail.png",
      "https://download.logo.wine/logo/Klarna/Klarna-Logo.wine.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/American_Express_logo_%282018%29.svg/2052px-American_Express_logo_%282018%29.svg.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Apple_Pay_logo.svg/1200px-Apple_Pay_logo.svg.png",
      "https://1000logos.net/wp-content/uploads/2021/05/Discover-logo.png",
    ],
  },
  {
    createdAt: "2025-03-10T11:24:38.264Z",
    id: "32",
    offerId: "131729710-online:en:GB:1364469",
    title: "Nike Shox TL Trainers Black Amarillo University Red, 10",
    description:
      "The Nike Shox TL takes mechanical cushioning to the next level.A recrafted version of the 2003 icon, it features breathable mesh in the upper, with full-length Nike Shox technology for optimal impact absorption and a bold look on the streets. Benefits:Nike Shox technology combines resilient, flexible columns with moderator plates for outstanding cushioning that compresses and regains its shape.A combination upper with a full TPU cage is a near-exact replica of the 2003 Nike Shox TL.Moulded overlays throughout the midfoot provide support and a snug fit.A TPU plate in the heel between the midsol",
    url: "https://track.shoparize.com/site.php?pos=0&page=0&sclid=WEB_ba282b4d-da51-45f2-a1fc-0874517d44e7&ps=60&product_id=9ddad70c-25ec-4de0-8a97-a7ea58d72b29&cs=product-popup_highlight&search=&cc=uk&url=https%3A%2F%2Fclick.linksynergy.com%2Flink%3Fid%3DbcLQBVEDxlA%26offerid%3D1775991.506871793099068799002950%26type%3D15%26murl%3Dhttps%253A%252F%252Fwww.office.co.uk%252Fview%252Fproduct%252Foffice_catalog%252F5%252C127%252F5196758006100&ga_client_id=1029153846.1742379287",
    image: "https://img.shoparize.com/products/9YadFTXFYHj.jpg",
    contentLanguage: "en",
    targetCountry: "GB",
    availability: "in stock",
    brand: "Nike",
    condition: "new",
    price: {
      value: "155",
      currency: "GBP",
    },
    isSale: true,
    freeShipping: false,
    category: "sportswear",
    shop: "Office.co.uk",
    shopImage: "https://i8.amplience.net/i/office/office-logo-jpg.jpg",
    rating: "2.4",
    payments: [
      "https://www.mastercard.com/content/dam/public/mastercardcom/vn/vi/logos/mastercard-og-image.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Visa_Inc._logo.svg/1024px-Visa_Inc._logo.svg.png",
      "https://rgb.vn/wp-content/uploads/2014/05/rgb_vn_new_branding_paypal_2014_logo_detail.png",
      "https://download.logo.wine/logo/Klarna/Klarna-Logo.wine.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Apple_Pay_logo.svg/1200px-Apple_Pay_logo.svg.png",
    ],
  },
  {
    createdAt: "2025-03-10T11:26:38.264Z",
    id: "33",
    offerId: "131729710-online:en:GB:1364469",
    title:
      "Nike Shox Men Shoes - Black - Size,  10 - Textile, Synthetics - Foot Locker",
    description:
      "The Nike Shox TL takes mechanical cushioning to the next level.A recrafted version of the 2003 icon, it features breathable mesh in the upper, with full-length Nike Shox technology for optimal impact absorption and a bold look on the streets. Benefits:Nike Shox technology combines resilient, flexible columns with moderator plates for outstanding cushioning that compresses and regains its shape.A combination upper with a full TPU cage is a near-exact replica of the 2003 Nike Shox TL.Moulded overlays throughout the midfoot provide support and a snug fit.A TPU plate in the heel between the midsol",
    url: "https://track.shoparize.com/site.php?pos=0&page=0&sclid=WEB_ba282b4d-da51-45f2-a1fc-0874517d44e7&ps=60&product_id=9ddad70c-25ec-4de0-8a97-a7ea58d72b29&cs=product-popup_highlight&search=&cc=uk&url=https%3A%2F%2Fclick.linksynergy.com%2Flink%3Fid%3DbcLQBVEDxlA%26offerid%3D1775991.506871793099068799002950%26type%3D15%26murl%3Dhttps%253A%252F%252Fwww.office.co.uk%252Fview%252Fproduct%252Foffice_catalog%252F5%252C127%252F5196758006100&ga_client_id=1029153846.1742379287",
    image: "https://img.shoparize.com/products/9YadFTXFYHj.jpg",
    contentLanguage: "en",
    targetCountry: "GB",
    availability: "in stock",
    brand: "Nike",
    condition: "new",
    price: {
      value: "149.99",
      currency: "GBP",
    },
    isSale: true,
    freeShipping: false,
    category: "sportswear",
    shop: "Footlocker.co.uk",
    shopImage:
      "https://brandlogos.net/wp-content/uploads/2022/01/foot_locker-logo-brandlogo.net_.png",
    rating: "1.6",
    payments: [
      "https://www.mastercard.com/content/dam/public/mastercardcom/vn/vi/logos/mastercard-og-image.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Visa_Inc._logo.svg/1024px-Visa_Inc._logo.svg.png",
      "https://rgb.vn/wp-content/uploads/2014/05/rgb_vn_new_branding_paypal_2014_logo_detail.png",
    ],
  }
];
